# Generated by Django 6.1.1 on 2026-09-06 15:05

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id_actividad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'db_table': 'actividad',
            },
        ),
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id_almacen', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'almacen',
            },
        ),
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('id_camion', models.AutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'camion',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('ruc', models.CharField(max_length=20, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresas/logos/')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'empresa',
            },
        ),
        migrations.CreateModel(
            name='ManoDeObra',
            fields=[
                ('id_mano_de_obra', models.AutoField(primary_key=True, serialize=False)),
                ('partida', models.CharField(max_length=7, unique=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'db_table': 'mano_de_obra',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id_material', models.AutoField(primary_key=True, serialize=False)),
                ('matricula', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'db_table': 'material',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('ruc', models.CharField(max_length=20, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('contacto', models.CharField(blank=True, max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'proveedor',
            },
        ),
        migrations.CreateModel(
            name='Recupero',
            fields=[
                ('id_recupero', models.AutoField(primary_key=True, serialize=False)),
                ('matricula', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'recupero',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='Suministro',
            fields=[
                ('id_suministro', models.AutoField(primary_key=True, serialize=False)),
                ('numero_suministro', models.CharField(db_index=True, max_length=20, unique=True)),
                ('medidor', models.CharField(blank=True, max_length=20)),
                ('distrito', models.CharField(blank=True, max_length=100)),
                ('monto_sum', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('estado', models.CharField(choices=[('asignado', 'Asignado'), ('ejecutado', 'Ejecutado'), ('devuelto', 'Devuelto')], default='asignado', max_length=20)),
                ('fecha_ejecucion', models.DateField(blank=True, null=True)),
                ('ejecutado_por', models.CharField(blank=True, max_length=150)),
                ('motivo_devolucion', models.TextField(blank=True)),
                ('observacion', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'suministro',
            },
        ),
        migrations.CreateModel(
            name='TipoTrabajo',
            fields=[
                ('id_tipo_trabajo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'db_table': 'tipo_trabajo',
            },
        ),
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id_devolucion', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('fecha_aprobacion', models.DateField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('almacen_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones_recibidas', to='core.almacen')),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='core.camion')),
            ],
            options={
                'db_table': 'devolucion',
            },
        ),
        migrations.AddField(
            model_name='camion',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='camiones', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='almacen',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='almacenes', to='core.empresa'),
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('mes', models.PositiveSmallIntegerField()),
                ('anio', models.PositiveSmallIntegerField()),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('cerrado', 'Cerrado')], default='borrador', max_length=20)),
                ('observacion', models.TextField(blank=True)),
                ('almacen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventarios', to='core.almacen')),
                ('camion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventarios', to='core.camion')),
            ],
            options={
                'db_table': 'inventario',
            },
        ),
        migrations.CreateModel(
            name='DetalleInventario',
            fields=[
                ('id_detalle_inventario', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_fisica', models.IntegerField()),
                ('cantidad_teorica', models.IntegerField()),
                ('diferencia', models.IntegerField()),
                ('observacion', models.TextField(blank=True)),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.inventario')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_inventario', to='core.material')),
            ],
            options={
                'db_table': 'detalle_inventario',
                'ordering': ['material__matricula'],
            },
        ),
        migrations.CreateModel(
            name='DetalleDevolucion',
            fields=[
                ('id_detalle_devolucion', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_solicitada', models.PositiveIntegerField()),
                ('cantidad_aprobada', models.PositiveIntegerField(default=0)),
                ('devolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.devolucion')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_devolucion', to='core.material')),
            ],
            options={
                'db_table': 'detalle_devolucion',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('fecha_aprobacion', models.DateField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('almacen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='core.almacen')),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='core.camion')),
            ],
            options={
                'db_table': 'pedido',
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id_detalle_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_solicitada', models.PositiveIntegerField()),
                ('cantidad_aprobada', models.PositiveIntegerField(default=0)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_pedido', to='core.material')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.pedido')),
            ],
            options={
                'db_table': 'detalle_pedido',
            },
        ),
        migrations.CreateModel(
            name='SST',
            fields=[
                ('id_sst', models.AutoField(primary_key=True, serialize=False)),
                ('sst', models.CharField(blank=True, max_length=7)),
                ('codigo', models.CharField(blank=True, db_index=True, max_length=20)),
                ('distrito', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_termino', models.DateField(blank=True, null=True)),
                ('monto_sst', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('actividad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ssts', to='core.actividad')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ssts', to='core.empresa')),
            ],
            options={
                'db_table': 'sst',
            },
        ),
        migrations.CreateModel(
            name='SuministroRecupero',
            fields=[
                ('id_suministro_recupero', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha', models.DateField()),
                ('recupero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suministros', to='core.recupero')),
                ('suministro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recuperos', to='core.suministro')),
            ],
            options={
                'db_table': 'suministro_recupero',
            },
        ),
        migrations.CreateModel(
            name='TipoTrabajoMaterialProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Tipo trabajo material',
                'verbose_name_plural': 'Tipo trabajos materiales',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.tipotrabajo',),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('clave', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('fcm_token', models.CharField(blank=True, max_length=500, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='core.empresa')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='core.rol')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='UploadConsumo',
            fields=[
                ('id_upload', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_upload', models.DateTimeField(auto_now=True)),
                ('nombre_archivo', models.CharField(blank=True, max_length=255)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('sst', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='upload_consumo', to='core.sst')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploads_consumo', to='core.usuario')),
            ],
            options={
                'db_table': 'upload_consumo',
            },
        ),
        migrations.CreateModel(
            name='TransferenciaAlmacen',
            fields=[
                ('id_transferencia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('observacion', models.TextField(blank=True)),
                ('almacen_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_entrada', to='core.almacen')),
                ('almacen_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_salida', to='core.almacen')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias', to='core.usuario')),
            ],
            options={
                'db_table': 'transferencia_almacen',
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='core.usuario'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='usuario_aprueba',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_aprobados', to='core.usuario'),
        ),
        migrations.CreateModel(
            name='MaterialMalogrado',
            fields=[
                ('id_malogrado', models.AutoField(primary_key=True, serialize=False)),
                ('folio_factura', models.CharField(max_length=50, unique=True)),
                ('fecha', models.DateField()),
                ('observacion', models.TextField(blank=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materiales_malogrados', to='core.almacen')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materiales_malogrados', to='core.proveedor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materiales_malogrados', to='core.usuario')),
            ],
            options={
                'db_table': 'material_malogrado',
            },
        ),
        migrations.CreateModel(
            name='LiquidacionSuministro',
            fields=[
                ('id_liquidacion', models.AutoField(primary_key=True, serialize=False)),
                ('suministro_externo', models.CharField(blank=True, max_length=20)),
                ('sst_externo', models.CharField(blank=True, max_length=20)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('observacion', models.TextField(blank=True)),
                ('suministro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones', to='core.suministro')),
                ('tipo_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones', to='core.tipotrabajo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones', to='core.usuario')),
            ],
            options={
                'db_table': 'liquidacion_suministro',
            },
        ),
        migrations.AddField(
            model_name='inventario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventarios', to='core.usuario'),
        ),
        migrations.CreateModel(
            name='IngresoTecsur',
            fields=[
                ('id_ingreso', models.AutoField(primary_key=True, serialize=False)),
                ('folio', models.CharField(max_length=50, unique=True)),
                ('fecha', models.DateField()),
                ('observacion', models.TextField(blank=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingresos', to='core.almacen')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingresos', to='core.proveedor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingresos_tecsur', to='core.usuario')),
            ],
            options={
                'db_table': 'ingreso_tecsur',
            },
        ),
        migrations.CreateModel(
            name='DevolucionTecsur',
            fields=[
                ('id_devolucion_tecsur', models.AutoField(primary_key=True, serialize=False)),
                ('folio', models.CharField(max_length=50, unique=True)),
                ('fecha', models.DateField()),
                ('observacion', models.TextField(blank=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones_tecsur', to='core.almacen')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones_tecsur', to='core.proveedor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones_tecsur', to='core.usuario')),
            ],
            options={
                'db_table': 'devolucion_tecsur',
            },
        ),
        migrations.AddField(
            model_name='devolucion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='core.usuario'),
        ),
        migrations.AddField(
            model_name='devolucion',
            name='usuario_aprueba',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devoluciones_aprobadas', to='core.usuario'),
        ),
        migrations.CreateModel(
            name='ConsumoMaterialSuministro',
            fields=[
                ('id_consumo_material', models.AutoField(primary_key=True, serialize=False)),
                ('suministro_externo', models.CharField(blank=True, max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha', models.DateField(auto_now_add=True)),
                ('liquidacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materiales_consumidos', to='core.liquidacionsuministro')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumos_suministro', to='core.material')),
                ('suministro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consumos_material', to='core.suministro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumos_suministro', to='core.usuario')),
            ],
            options={
                'db_table': 'consumo_material_suministro',
            },
        ),
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id_consumo', models.AutoField(primary_key=True, serialize=False)),
                ('suministro', models.CharField(blank=True, max_length=50)),
                ('fecha', models.DateField()),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumos', to='core.camion')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='core.uploadconsumo')),
                ('usuario_consume', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumos_realizados', to='core.usuario')),
            ],
            options={
                'db_table': 'consumo',
                'unique_together': {('upload', 'usuario_consume', 'camion', 'suministro', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='UsuarioCamion',
            fields=[
                ('id_usuario_camion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='core.camion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='core.usuario')),
            ],
            options={
                'db_table': 'usuario_camion',
            },
        ),
        migrations.CreateModel(
            name='LiquidacionPartida',
            fields=[
                ('id_liquidacion_partida', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('liquidacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='core.liquidacionsuministro')),
                ('mano_de_obra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones', to='core.manodeobra')),
            ],
            options={
                'db_table': 'liquidacion_partida',
                'unique_together': {('liquidacion', 'mano_de_obra')},
            },
        ),
        migrations.CreateModel(
            name='DetalleIngresoTecsur',
            fields=[
                ('id_detalle_ingreso', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('ingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.ingresotecsur')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_ingreso', to='core.material')),
            ],
            options={
                'db_table': 'detalle_ingreso_tecsur',
                'unique_together': {('ingreso', 'material')},
            },
        ),
        migrations.CreateModel(
            name='DetalleDevolucionTecsur',
            fields=[
                ('id_detalle_dev_tecsur', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('devolucion_tecsur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.devoluciontecsur')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_dev_tecsur', to='core.material')),
            ],
            options={
                'db_table': 'detalle_devolucion_tecsur',
                'unique_together': {('devolucion_tecsur', 'material')},
            },
        ),
        migrations.CreateModel(
            name='DetalleConsumo',
            fields=[
                ('id_detalle_consumo', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('consumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.consumo')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_consumo', to='core.material')),
            ],
            options={
                'db_table': 'detalle_consumo',
                'unique_together': {('consumo', 'material')},
            },
        ),
        migrations.CreateModel(
            name='DetalleMaterialMalogrado',
            fields=[
                ('id_detalle_malogrado', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_malogrado', to='core.material')),
                ('malogrado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.materialmalogrado')),
            ],
            options={
                'db_table': 'detalle_material_malogrado',
                'unique_together': {('malogrado', 'material')},
            },
        ),
        migrations.CreateModel(
            name='StockAlmacen',
            fields=[
                ('id_stock_almacen', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='core.almacen')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks_almacen', to='core.material')),
            ],
            options={
                'db_table': 'stock_almacen',
                'unique_together': {('almacen', 'material')},
            },
        ),
        migrations.CreateModel(
            name='StockCamion',
            fields=[
                ('id_stock', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='core.camion')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='core.material')),
            ],
            options={
                'db_table': 'stock_camion',
                'unique_together': {('camion', 'material')},
            },
        ),
        migrations.CreateModel(
            name='SuministroManoDeObra',
            fields=[
                ('id_suministro_mano_de_obra', models.AutoField(primary_key=True, serialize=False)),
                ('mano_de_obra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suministros', to='core.manodeobra')),
                ('suministro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mano_de_obra', to='core.suministro')),
            ],
            options={
                'db_table': 'suministro_mano_de_obra',
                'unique_together': {('suministro', 'mano_de_obra')},
            },
        ),
        migrations.CreateModel(
            name='SuministroTipoTrabajo',
            fields=[
                ('id_suministro_tipo_trabajo', models.AutoField(primary_key=True, serialize=False)),
                ('suministro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipos_trabajo', to='core.suministro')),
                ('tipo_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suministros', to='core.tipotrabajo')),
            ],
            options={
                'db_table': 'suministro_tipo_trabajo',
                'unique_together': {('suministro', 'tipo_trabajo')},
            },
        ),
        migrations.CreateModel(
            name='ActividadTipoTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipos_trabajo', to='core.actividad')),
                ('tipo_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actividades', to='core.tipotrabajo')),
            ],
            options={
                'db_table': 'actividad_tipo_trabajo',
                'unique_together': {('actividad', 'tipo_trabajo')},
            },
        ),
        migrations.CreateModel(
            name='TipoTrabajoManoDeObra',
            fields=[
                ('id_tipo_trabajo_mano_de_obra', models.AutoField(primary_key=True, serialize=False)),
                ('mano_de_obra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipos_trabajo', to='core.manodeobra')),
                ('tipo_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partidas', to='core.tipotrabajo')),
            ],
            options={
                'db_table': 'tipo_trabajo_mano_de_obra',
                'unique_together': {('tipo_trabajo', 'mano_de_obra')},
            },
        ),
        migrations.CreateModel(
            name='TipoTrabajoMaterial',
            fields=[
                ('id_tipo_trabajo_material', models.AutoField(primary_key=True, serialize=False)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipos_trabajo', to='core.material')),
                ('tipo_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materiales', to='core.tipotrabajo')),
            ],
            options={
                'db_table': 'tipo_trabajo_material',
                'unique_together': {('tipo_trabajo', 'material')},
            },
        ),
        migrations.CreateModel(
            name='DetalleTransferencia',
            fields=[
                ('id_detalle_transferencia', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_transferencia', to='core.material')),
                ('transferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.transferenciaalmacen')),
            ],
            options={
                'db_table': 'detalle_transferencia',
                'unique_together': {('transferencia', 'material')},
            },
        ),
        migrations.CreateModel(
            name='SSTSuministro',
            fields=[
                ('id_sst_suministro', models.AutoField(primary_key=True, serialize=False)),
                ('sst', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sst_suministros', to='core.sst')),
                ('suministro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sst_suministros', to='core.suministro')),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suministros_asignados', to='core.usuario')),
            ],
            options={
                'db_table': 'sst_suministro',
                'unique_together': {('sst', 'suministro')},
            },
        ),
        migrations.CreateModel(
            name='SSTEncargado',
            fields=[
                ('id_sst_encargado', models.AutoField(primary_key=True, serialize=False)),
                ('sst', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sst_encargados', to='core.sst')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sst_encargados', to='core.usuario')),
            ],
            options={
                'db_table': 'sst_encargado',
                'unique_together': {('sst', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='PlanoSST',
            fields=[
                ('id_plano', models.AutoField(primary_key=True, serialize=False)),
                ('sst_codigo', models.CharField(db_index=True, max_length=20)),
                ('elementos', models.JSONField(default=list)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planos', to='core.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planos', to='core.usuario')),
            ],
            options={
                'db_table': 'plano_sst',
                'unique_together': {('empresa', 'sst_codigo')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='inventario',
            unique_together={('almacen', 'mes', 'anio'), ('camion', 'mes', 'anio')},
        ),
    ]
