# Generated by Django 6.1.1 on 2026-09-12 14:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sst_fecha_ejecucion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraspasoCamion',
            fields=[
                ('id_traspaso', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('observacion', models.TextField(blank=True)),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traspasos', to='core.camion')),
                ('usuario_entrega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traspasos_entregados', to='core.usuario')),
                ('usuario_recibe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traspasos_recibidos', to='core.usuario')),
            ],
            options={
                'db_table': 'traspaso_camion',
                'ordering': ['-fecha', '-id_traspaso'],
            },
        ),
        migrations.CreateModel(
            name='DetalleTraspasoCamion',
            fields=[
                ('id_detalle_traspaso', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_traspaso', to='core.material')),
                ('traspaso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.traspasocamion')),
            ],
            options={
                'db_table': 'detalle_traspaso_camion',
                'ordering': ['material__matricula'],
                'unique_together': {('traspaso', 'material')},
            },
        ),
    ]
