# Generated by Django 6.1.1 on 2026-09-13 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_empresa_encossa'),
    ]

    operations = [
        migrations.AddField(
            model_name='recupero',
            name='unidad',
            field=models.CharField(default='UND', max_length=10),
        ),
    ]
