# Generated by Django 6.1.1 on 2026-09-14 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_recupero_unidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipotrabajomanodeobra',
            name='cantidad_inicial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='tipotrabajomaterial',
            name='cantidad_inicial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
