# Generated by Django 6.0 on 2026-09-16 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_pastorales_correctos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividadtipotrabajo',
            options={'ordering': ['orden', 'tipo_trabajo__nombre']},
        ),
        migrations.AddField(
            model_name='actividadtipotrabajo',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
