# Generated by Django 6.0 on 2026-09-16 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_orden_tipos_trabajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol_secundario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios_secundarios', to='core.rol'),
        ),
    ]
