# Generated by Django 6.1.1 on 2026-09-16 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_saldo_de_prueba'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacionsuministro',
            name='comentario',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sst',
            name='hora_ejecucion',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CuadernoObra',
            fields=[
                ('id_cuaderno', models.AutoField(primary_key=True, serialize=False)),
                ('sst_codigo', models.CharField(max_length=20)),
                ('numero', models.PositiveIntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuadernos', to='core.empresa')),
            ],
            options={
                'db_table': 'cuaderno_obra',
                'unique_together': {('empresa', 'numero'), ('empresa', 'sst_codigo')},
            },
        ),
    ]
