# Generated by Django 6.1.1 on 2026-09-19 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_renombrar_otros_cabria'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorreccionLiquidacion',
            fields=[
                ('id_correccion', models.AutoField(primary_key=True, serialize=False)),
                ('suministro_externo', models.CharField(blank=True, max_length=20)),
                ('sst_externo', models.CharField(blank=True, max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('fecha_anterior', models.DateField(blank=True, null=True)),
                ('anterior', models.JSONField(default=dict)),
                ('cambios', models.TextField(blank=True)),
                ('suministro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correcciones_liquidacion', to='core.suministro')),
                ('tipo_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correcciones_liquidacion', to='core.tipotrabajo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correcciones_liquidacion', to='core.usuario')),
                ('usuario_anterior', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones_corregidas', to='core.usuario')),
            ],
            options={
                'db_table': 'correccion_liquidacion',
                'ordering': ['-fecha'],
            },
        ),
    ]
