# Generated by Django 6.1.1 on 2026-09-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_registro_correccion_liquidacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='varios_postes',
            field=models.BooleanField(default=False),
        ),
    ]
