# Generated by Django 6.1.1 on 2026-09-22 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_actividad_varios_postes'),
    ]

    operations = [
        migrations.AddField(
            model_name='manodeobra',
            name='ambito',
            field=models.CharField(choices=[('poste', 'Por poste'), ('sst', 'Por SST')], default='poste', max_length=10),
        ),
    ]
