# Generated by Django 6.1.1 on 2026-09-23 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_ambito_de_partida'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipotrabajomanodeobra',
            options={'ordering': ['orden', 'id_tipo_trabajo_mano_de_obra']},
        ),
        migrations.AddField(
            model_name='tipotrabajomanodeobra',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
