# Generated by Django 6.1.1 on 2026-09-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_orden_de_partidas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sstsuministro',
            options={'ordering': ['orden', 'id_sst_suministro']},
        ),
        migrations.AddField(
            model_name='sstsuministro',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
