# Generated by Django 6.0 on 2026-09-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_orden_de_puntos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suministro',
            name='numero_suministro',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
