# Generated by Django 6.1.1 on 2026-09-28 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_suministro_numero_suministro'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='de_encargado',
            field=models.BooleanField(default=False),
        ),
    ]
