# Generated by Django 6.1.1 on 2026-09-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_actividad_de_encargado'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacionsuministro',
            name='medidas',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='material',
            name='es_agregado',
            field=models.BooleanField(default=False),
        ),
    ]
