# Generated by Django 6.1.1 on 2026-09-29 12:42

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_cantidades_con_decimales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleingresotecsur',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
