# Generated by Django 6.1.1 on 2026-09-29 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_ingreso_con_decimales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleinventario',
            name='cantidad_fisica',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='detalleinventario',
            name='cantidad_teorica',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='detalleinventario',
            name='diferencia',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
