# Generated by Django 6.1.1 on 2026-10-02 15:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_inventario_con_decimales'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionAgregado',
            fields=[
                ('id_asignacion', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('origen', models.CharField(choices=[('almacen', 'Desde almacén'), ('camion', 'Desde el camión')], max_length=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.TextField(blank=True)),
                ('anulada', models.BooleanField(default=False)),
                ('fecha_anulacion', models.DateTimeField(blank=True, null=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_agregado', to='core.almacen')),
                ('anulada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agregados_anulados', to='core.usuario')),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_agregado', to='core.camion')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_agregado', to='core.material')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agregados_registrados', to='core.usuario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agregados_recibidos', to='core.usuario')),
            ],
            options={
                'db_table': 'asignacion_agregado',
                'ordering': ['-fecha', '-id_asignacion'],
            },
        ),
    ]
