# Generated by Django 6.1.1 on 2026-10-05 16:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_asignacion_agregado'),
    ]

    operations = [
        migrations.CreateModel(
            name='EPP',
            fields=[
                ('id_epp', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('unidad', models.CharField(default='UND', max_length=20)),
                ('talla', models.CharField(blank=True, max_length=10)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'epp',
                'ordering': ['descripcion', 'id_epp'],
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='dni',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='IngresoEPP',
            fields=[
                ('id_ingreso_epp', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('observacion', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingresos_epp', to='core.almacen')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingresos_epp', to='core.usuario')),
            ],
            options={
                'db_table': 'ingreso_epp',
                'ordering': ['-fecha', '-id_ingreso_epp'],
            },
        ),
        migrations.CreateModel(
            name='DetalleIngresoEPP',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('epp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingresos', to='core.epp')),
                ('ingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.ingresoepp')),
            ],
            options={
                'db_table': 'detalle_ingreso_epp',
            },
        ),
        migrations.CreateModel(
            name='StockEPP',
            fields=[
                ('id_stock_epp', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks_epp', to='core.almacen')),
                ('epp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='core.epp')),
            ],
            options={
                'db_table': 'stock_epp',
                'unique_together': {('almacen', 'epp')},
            },
        ),
    ]
