# Generated by Django 6.1.1 on 2026-10-05 17:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_epp_y_datos_de_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoEPP',
            fields=[
                ('id_pedido_epp', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('nuevo', 'Nuevo'), ('cambio', 'Cambio')], max_length=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=10)),
                ('motivo', models.TextField(blank=True)),
                ('observacion', models.TextField(blank=True)),
                ('foto', models.BinaryField(blank=True, null=True)),
                ('foto_tipo', models.CharField(blank=True, max_length=30)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('observacion_aprobacion', models.TextField(blank=True)),
                ('almacen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_epp', to='core.almacen')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_epp', to='core.usuario')),
                ('usuario_aprueba', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_epp_aprobados', to='core.usuario')),
            ],
            options={
                'db_table': 'pedido_epp',
                'ordering': ['-fecha', '-id_pedido_epp'],
            },
        ),
        migrations.CreateModel(
            name='DetallePedidoEPP',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_solicitada', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('cantidad_aprobada', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('epp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='core.epp')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.pedidoepp')),
            ],
            options={
                'db_table': 'detalle_pedido_epp',
            },
        ),
    ]
