# Generated by Django 6.1.1 on 2026-10-06 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_pedidos_epp'),
    ]

    operations = [
        migrations.AddField(
            model_name='camion',
            name='vence_revision_tecnica',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='camion',
            name='vence_soat',
            field=models.DateField(blank=True, null=True),
        ),
    ]
