# Generated by Django 6.1.1 on 2026-10-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_vencimientos_de_unidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoepp',
            name='origen',
            field=models.CharField(choices=[('pedido', 'Pedido'), ('asignacion', 'Asignación')], default='pedido', max_length=12),
        ),
    ]
