# Generated by Django 6.1.1 on 2026-10-07 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_origen_del_pedido_epp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoEmergencia',
            fields=[
                ('id_contacto', models.AutoField(primary_key=True, serialize=False)),
                ('superior_nombre', models.CharField(blank=True, max_length=150)),
                ('superior_telefono', models.CharField(blank=True, max_length=30)),
                ('medico_nombre', models.CharField(blank=True, max_length=150)),
                ('medico_telefono', models.CharField(blank=True, max_length=30)),
                ('centro_medico', models.CharField(blank=True, max_length=200)),
                ('centro_medico_telefono', models.CharField(blank=True, max_length=30)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contacto_emergencia', to='core.empresa')),
            ],
            options={
                'db_table': 'contacto_emergencia',
            },
        ),
        migrations.CreateModel(
            name='IPC',
            fields=[
                ('id_ipc', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('tarea', models.TextField()),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado')], default='abierto', max_length=10)),
                ('formato_codigo', models.CharField(max_length=30)),
                ('formato_version', models.CharField(max_length=10)),
                ('datos', models.JSONField(blank=True, default=dict)),
                ('observaciones', models.TextField(blank=True)),
                ('hora_cierre', models.TimeField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('coordinador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ipcs_coordinados', to='core.usuario')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ipcs', to='core.empresa')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ipcs_responsable', to='core.usuario')),
            ],
            options={
                'db_table': 'ipc',
                'ordering': ['-fecha', '-id_ipc'],
            },
        ),
        migrations.CreateModel(
            name='IPCParticipante',
            fields=[
                ('id_participante', models.AutoField(primary_key=True, serialize=False)),
                ('dni', models.CharField(blank=True, max_length=15)),
                ('cargo', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('conforme', 'Conforme')], default='pendiente', max_length=10)),
                ('metodo', models.CharField(blank=True, choices=[('app', 'Desde su app'), ('equipo', 'En el equipo del responsable')], max_length=10)),
                ('confirmado', models.DateTimeField(blank=True, null=True)),
                ('firma', models.BinaryField(blank=True, null=True)),
                ('ipc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='core.ipc')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ipcs_participante', to='core.usuario')),
            ],
            options={
                'db_table': 'ipc_participante',
                'ordering': ['id_participante'],
                'unique_together': {('ipc', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='IPCSST',
            fields=[
                ('id_ipc_sst', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(blank=True, max_length=250)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('agregada', models.DateTimeField(auto_now_add=True)),
                ('ipc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssts', to='core.ipc')),
                ('sst', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ipcs', to='core.sst')),
            ],
            options={
                'db_table': 'ipc_sst',
                'ordering': ['orden', 'id_ipc_sst'],
                'unique_together': {('ipc', 'sst')},
            },
        ),
    ]
