# Generated by Django 6.1.1 on 2026-10-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_ipc'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoepp',
            name='foto_archivo',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
