# Generated by Django 6.1.1 on 2026-10-10 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_foto_en_cloudinary'),
    ]

    operations = [
        migrations.AddField(
            model_name='camion',
            name='combustible',
            field=models.CharField(blank=True, choices=[('gasolina', 'Gasolina'), ('diesel', 'Diésel'), ('glp', 'GLP'), ('gnv', 'GNV')], max_length=10),
        ),
        migrations.CreateModel(
            name='JornadaCamion',
            fields=[
                ('id_jornada', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('km_salida', models.PositiveIntegerField()),
                ('foto_salida', models.CharField(max_length=255)),
                ('hora_salida', models.DateTimeField(auto_now_add=True)),
                ('trabajo_interno', models.TextField(blank=True)),
                ('km_cierre', models.PositiveIntegerField(blank=True, null=True)),
                ('foto_cierre', models.CharField(blank=True, max_length=255)),
                ('hora_cierre', models.DateTimeField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True)),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jornadas', to='core.camion')),
                ('chofer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jornadas_chofer', to='core.usuario')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jornadas_responsable', to='core.usuario')),
            ],
            options={
                'db_table': 'jornada_camion',
                'ordering': ['-hora_salida'],
            },
        ),
        migrations.CreateModel(
            name='CargaCombustible',
            fields=[
                ('id_carga', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('km', models.PositiveIntegerField()),
                ('combustible', models.CharField(choices=[('gasolina', 'Gasolina'), ('diesel', 'Diésel'), ('glp', 'GLP'), ('gnv', 'GNV')], max_length=10)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tanque_lleno', models.BooleanField(default=False)),
                ('grifo', models.CharField(blank=True, max_length=150)),
                ('foto', models.CharField(max_length=255)),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargas', to='core.camion')),
                ('chofer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargas_combustible', to='core.usuario')),
                ('jornada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cargas', to='core.jornadacamion')),
            ],
            options={
                'db_table': 'carga_combustible',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='JornadaSST',
            fields=[
                ('id_jornada_sst', models.AutoField(primary_key=True, serialize=False)),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssts', to='core.jornadacamion')),
                ('sst', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jornadas', to='core.sst')),
            ],
            options={
                'db_table': 'jornada_sst',
                'unique_together': {('jornada', 'sst')},
            },
        ),
    ]
